// <auto-generated />
using System;
using AspNetWebServer.Model.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AspNetWebServer.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gin");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AspNetWebServer.Model.Data.Pc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Online")
                        .HasColumnType("boolean");

                    b.Property<string>("hostname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id", "hostname")
                        .HasDatabaseName("Pc_Id_Hostname_Index");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Id", "hostname"), "btree");

                    b.ToTable("Pcs");
                });

            modelBuilder.Entity("AspNetWebServer.Model.Data.ProcessMonitoring.MountedProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MonutedIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PcSenderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProcessId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PcSenderId");

                    b.HasIndex("Id", "MonutedIndex")
                        .HasDatabaseName("MountedProcess_Id_MonutedIndex_Index");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Id", "MonutedIndex"), "btree");

                    b.ToTable("MountedProcesses");
                });

            modelBuilder.Entity("AspNetWebServer.Model.Data.ProcessMonitoring.ProcessAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MountedProcessId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PcSenderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProcessId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TimeStarted")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MountedProcessId");

                    b.HasIndex("PcSenderId");

                    b.HasIndex("Id", "Date", "MountedProcessId")
                        .HasDatabaseName("ProcessAction_Id_Date_MountedProcessId_Index");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Id", "Date", "MountedProcessId"), "btree");

                    b.ToTable("ProcessActions");
                });

            modelBuilder.Entity("AspNetWebServer.Model.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PCId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PCId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AspNetWebServer.Model.Data.Utilization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("CPU_load")
                        .HasColumnType("real");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PcId")
                        .HasColumnType("integer");

                    b.Property<float>("RAM")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("PcId");

                    b.ToTable("Utilizations");
                });

            modelBuilder.Entity("AspNetWebServer.Model.Data.infoSecuritySpecialist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("infoSecuritySpecialists");
                });

            modelBuilder.Entity("AspNetWebServer.Model.Data.ProcessMonitoring.MountedProcess", b =>
                {
                    b.HasOne("AspNetWebServer.Model.Data.Pc", "PcSender")
                        .WithMany()
                        .HasForeignKey("PcSenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PcSender");
                });

            modelBuilder.Entity("AspNetWebServer.Model.Data.ProcessMonitoring.ProcessAction", b =>
                {
                    b.HasOne("AspNetWebServer.Model.Data.ProcessMonitoring.MountedProcess", "MountedProces")
                        .WithMany("ProcessActions")
                        .HasForeignKey("MountedProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspNetWebServer.Model.Data.Pc", "PcSender")
                        .WithMany()
                        .HasForeignKey("PcSenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MountedProces");

                    b.Navigation("PcSender");
                });

            modelBuilder.Entity("AspNetWebServer.Model.Data.User", b =>
                {
                    b.HasOne("AspNetWebServer.Model.Data.Pc", "PC")
                        .WithMany()
                        .HasForeignKey("PCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PC");
                });

            modelBuilder.Entity("AspNetWebServer.Model.Data.Utilization", b =>
                {
                    b.HasOne("AspNetWebServer.Model.Data.Pc", "Pc")
                        .WithMany()
                        .HasForeignKey("PcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pc");
                });

            modelBuilder.Entity("AspNetWebServer.Model.Data.ProcessMonitoring.MountedProcess", b =>
                {
                    b.Navigation("ProcessActions");
                });
#pragma warning restore 612, 618
        }
    }
}
