// <auto-generated />
using System;
using AspNetWebServer.Model.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspNetWebServer.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AspNetWebServer.Model.Data.Pc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Online")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("hostname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Pcs");
                });

            modelBuilder.Entity("AspNetWebServer.Model.Data.ProcessMonitoring.MountedProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MonutedIndex")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PcSenderId")
                        .HasColumnType("int");

                    b.Property<int>("ProcessId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PcSenderId");

                    b.ToTable("MountedProcesses");
                });

            modelBuilder.Entity("AspNetWebServer.Model.Data.ProcessMonitoring.ProcessAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MountedProcessId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PcSenderId")
                        .HasColumnType("int");

                    b.Property<int>("ProcessId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStarted")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("MountedProcessId");

                    b.HasIndex("PcSenderId");

                    b.ToTable("ProcessActions");
                });

            modelBuilder.Entity("AspNetWebServer.Model.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PCId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PCId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AspNetWebServer.Model.Data.Utilization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<float>("CPU_load")
                        .HasColumnType("float");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PcId")
                        .HasColumnType("int");

                    b.Property<float>("RAM")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("PcId");

                    b.ToTable("Utilizations");
                });

            modelBuilder.Entity("AspNetWebServer.Model.Data.ProcessMonitoring.MountedProcess", b =>
                {
                    b.HasOne("AspNetWebServer.Model.Data.Pc", "PcSender")
                        .WithMany()
                        .HasForeignKey("PcSenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PcSender");
                });

            modelBuilder.Entity("AspNetWebServer.Model.Data.ProcessMonitoring.ProcessAction", b =>
                {
                    b.HasOne("AspNetWebServer.Model.Data.ProcessMonitoring.MountedProcess", "MountedProcess")
                        .WithMany()
                        .HasForeignKey("MountedProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspNetWebServer.Model.Data.Pc", "PcSender")
                        .WithMany()
                        .HasForeignKey("PcSenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MountedProcess");

                    b.Navigation("PcSender");
                });

            modelBuilder.Entity("AspNetWebServer.Model.Data.User", b =>
                {
                    b.HasOne("AspNetWebServer.Model.Data.Pc", "PC")
                        .WithMany()
                        .HasForeignKey("PCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PC");
                });

            modelBuilder.Entity("AspNetWebServer.Model.Data.Utilization", b =>
                {
                    b.HasOne("AspNetWebServer.Model.Data.Pc", "Pc")
                        .WithMany()
                        .HasForeignKey("PcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pc");
                });
#pragma warning restore 612, 618
        }
    }
}
